### ISSUE TITLE
Progress Report

### ISSUE THREAD

**Issue by vanhauser-thc** [AFLplusplus/Grammar-Mutator#1]
Hi Shengtuo,

please put your weekly progress reports in this issue.
Besides, I have not seen any progress the last 5 days. Do you need assistance?

**Comment by andreafioraldi** [comment]
The repo is now public

**Comment by h1994st** [comment]
> For the blob mutations, borrow this function https://github.com/AFLplusplus/AFLplusplus/blob/stable/examples/custom_mutators/custom_mutator_helpers.h#L24
> 
> 
> 
> It does not change the size of the mutated input part.

I will try it later. Thanks!

**Comment by h1994st** [comment]
May close this issue, as GSoC ends.
