### ISSUE TITLE
Test compilation error

### ISSUE THREAD

**Issue by trust1995** [AFLplusplus/Grammar-Mutator#27]
When compilings with ENABLE_TESTING=ON, I get the following issue:

`<some_path>/Grammar-Mutator/include/custom_mutator.h:26:9: error: empty struct has size 0 in C, size 1 in C++ [-Werror,-Wextern-c-compat]
typedef struct afl {
        ^
1 error generated.
make[2]: *** [tests/CMakeFiles/test_custom_mutator.dir/test_custom_mutator.cpp.o] Error 1
make[1]: *** [tests/CMakeFiles/test_custom_mutator.dir/all] Error 2
make: *** [all] Error 2`

I think we need to remove this error somehow inside the code. 

BTW I use the default Xcode compiler.

**Comment by vanhauser-thc** [comment]
xcode is crippled. if you use a real compiler it works with gcc and clang. I feel sorry for you ;)
