### ISSUE TITLE
A question about convert the ASCII

### ISSUE THREAD

**Issue by DuckRui** [AFLplusplus/Grammar-Mutator#29]
Hi，I had a problem when I using this tool. 
I want use some numbers (eg. 1, 2, 3 ......) as a seed content then I will send it to a network server to fuzzing. But I found when I use socket to send it , the number will change to ASCII. I want the number can keep hex model(eg. 1 -> 01, 30 -> 30).
If you could tell me, think you very much.

**Comment by h1994st** [comment]
Hi @DuckRui , I did not quite understand your problem.

Do you mean that, for your given grammar file, the generated test case is different from what you expected?

Can you provide more details about your setup, grammar file, expected output, etc.?

**Comment by DuckRui** [comment]
> 嗨@DuckRui，我不太明白你的问题。
> 
> 您的意思是，对于您给定的语法文件，生成的测试用例与您预期的不同吗？
> 
> 您能否提供有关您的设置、语法文件、预期输出等的更多详细信息？

Thank you for your reply. 
This is my setup
![image](https://user-images.githubusercontent.com/41203418/120338831-2a8da980-c327-11eb-8102-127eba2ae30e.png)

And , this is output
![image](https://user-images.githubusercontent.com/41203418/120339445-b56ea400-c327-11eb-8820-8268ef578521.png)

But actually，I hope it will not change to ASCII . Such as I put the number 2 the output will become 02,  but not 32(this is number 2's ASCII)

**Comment by DuckRui** [comment]
> Hi @DuckRui , I did not quite understand your problem.
> 
> Do you mean that, for your given grammar file, the generated test case is different from what you expected?
> 
> Can you provide more details about your setup, grammar file, expected output, etc.?

Maybe this python file can help you understand what I mean. But you need to run it. This output is my expected output. Thank you again.
[https://github.com/DuckRui/tools/blob/main/test.py](url)

**Comment by domenukk** [comment]
I think what you try to do is to not specify numbers in acii, but in bytes, correct? Maybe try something like `"\01"`? (Not sure if that would work, though :) )

**Comment by DuckRui** [comment]
> I think what you try to do is to not specify numbers in acii, but in bytes, correct? Maybe try something like `"\01"`? (Not sure if that would work, though :) )

Yes! This what I want, but I don not konw how to define it in my setup file. When I want to use "\01", as "\\" is a Escape character, json will refuse me= =I have to change it to "\\\\01". So can you teach me how to define it in setup file. Thank you again.

**Comment by h1994st** [comment]
Hi @DuckRui ,

The reason is that JSON does not support hex escape like `\xNN`, as indicated in [this post](https://stackoverflow.com/questions/4296041/simplejson-loads-get-invalid-escape-x) and [JSON documentation](https://www.json.org/json-en.html).

We currently only support grammar files in JSON and process them using a Python script, so hex characters cannot be embedded into the grammar file.

One workaround is to use the Unicode escape in JSON by converting `\xNN` to `\u00NN`, except for the null character `\x00` (e.g., `\u0000`).

~~To support `\u0000`, I need to change the Python script that processes the grammar file.~~ (see 354762e18b40e25fb34332f7937f4de19562c137)

**Comment by h1994st** [comment]
Please checkout the latest `dev` branch: 354762e18b40e25fb34332f7937f4de19562c137 to see if it works for you now.

**Comment by DuckRui** [comment]
> Hi @DuckRui ,
> 
> The reason is that JSON does not support hex escape like `\xNN`, as indicated in [this post](https://stackoverflow.com/questions/4296041/simplejson-loads-get-invalid-escape-x) and [JSON documentation](https://www.json.org/json-en.html).
> 
> We currently only support grammar files in JSON and process them using a Python script, so hex characters cannot be embedded into the grammar file.
> 
> One workaround is to use the Unicode escape in JSON by converting `\xNN` to `\u00NN`, except for the null character `\x00` (e.g., `\u0000`).
> 
> ~To support `\u0000`, I need to change the Python script that processes the grammar file.~ (see [354762e](https://github.com/AFLplusplus/Grammar-Mutator/commit/354762e18b40e25fb34332f7937f4de19562c137))

Thank you! This is the perfect solution to my problem

**Comment by h1994st** [comment]
Great! I will close this issue :)
