### ISSUE TITLE
A question about data length

### ISSUE THREAD

**Issue by DuckRui** [AFLplusplus/Grammar-Mutator#30]
Hi，I had a problem when I using Grammar-Mutator.
I want define a long hex in my setup file, like this
![image](https://user-images.githubusercontent.com/41203418/121221531-3eea1d00-c8b8-11eb-8a68-088b425d5109.png)

But when I use it in afl++, the program ran there will meet a bug, like this
![image](https://user-images.githubusercontent.com/41203418/121221697-650fbd00-c8b8-11eb-9860-48d6bbae90e1.png)
I change the code to printf the "ret". In normal ,the "ret" should be 1. But in my program "ret" is 0, like this
![image](https://user-images.githubusercontent.com/41203418/121221850-94262e80-c8b8-11eb-83c8-c230dcee59e2.png)
As "ret" is 0, the program will not run in Grammar-Mutator mode. So can you help me?  Thank you very much.

**Comment by DuckRui** [comment]
I seem know the reason. 
The real reason is hex datas have range from "\u0000"-"\u007f", So if I use data like "\u0080" will report error.

**Comment by h1994st** [comment]
Busy during the weekday. Just got a chance to look at this issue.

It should be a parsing issue as noted by you (see `af_custom_queue_get` in [`grammar_mutator.c`](https://github.com/AFLplusplus/Grammar-Mutator/blob/dev/src/grammar_mutator.c#L187-L189)).

It seems you have identified the reason. I will close this issue then. Feel free to reopen it if the issue still exists.
