### ISSUE TITLE
How to add extras dynamically during fuzzing

### ISSUE THREAD

**Issue by BrieflyX** [AFLplusplus/Grammar-Mutator#32]
As we know, naive afl would add some extras to `auto_extras` directory in queue and use them as a 'dynamic dictionary'.
I would like to implement this function also in grammar mutator, then when the fuzzer extracts some strings during execution, they could be passed to this mutator.
Are there any plan to make this feature ? Or I have to repeat modifying the grammar json file and rebuilding the `.so` library.

**Comment by vanhauser-thc** [comment]
you receive the afl struct pointer in the custom mutator init. you can copy that pointer and access anything you need from there inside your fuzzer.
look at the honggfuzz custom mutator which copies new dictionary entries, so basically exactly what you want.

**Comment by BrieflyX** [comment]
OK, I guess I have to integrate this function into the grammar mutator since I still need structed input.
