### ISSUE TITLE
Is it possible to automatically eliminate indirect left-recursion

### ISSUE THREAD

**Issue by yikesoftware** [AFLplusplus/Grammar-Mutator#38]
I generated the Lua grammar file using the following command: 

`python3 nautilus_py_grammar_to_json.py . /nautilus_py_grammars/lua.py . /lua.json`

But when compiling it prompts :

> `make GRAMMAR_FILE=grammars/lua.json`

```
error(119): /home/eqqie/Fuzz/Grammar-Mutator/grammars/Grammar.g4::: The following sets of rules are mutually left-recursive [node_FUNCTIONCALL, node_EXPR]
```

Even though I can manually eliminate such easy **indirect left-recursion**, it's a big headache for complex syntax, is it currently possible to do it automatically? 😂

**Comment by h1994st** [comment]
Hi @yikesoftware 

You may want to reach out to the ANTLR4 community about this issue, by attaching the generated `Grammar.g4` file.

There is an old issue #28 that also met the left-recursion issues. Maybe it can give you some hints.
