### ISSUE TITLE
Does this mutator uses genetic algorithm?

### ISSUE THREAD

**Issue by simbirsoft-evgeniy-shvetsov** [AFLplusplus/Grammar-Mutator#39]
I suppose it is, so I am sorry for such a stupid question, but I am forced to ask it.

Can it be 100% confirmed that this mutator uses a genetic algorithm?

**Comment by h1994st** [comment]
Wrong repo:) This mutator alone has no relationship with the genetic algorithm.

You may refer to [AFL++](https://github.com/AFLplusplus/AFLplusplus/blob/stable/docs/afl-fuzz_approach.md) for more details

**Comment by h1994st** [comment]
Closed. No response from the issue author.
