### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by 20urc3** [AFLplusplus/Grammar-Mutator#46]
Hi,

I'm trying to use the tool to generate Javascript testcases, however when I run `make GRAMMAR_FILE=grammars/javascript.json` 
I got the following result: `UnicodeEncodeError: 'latin-1' codec can't encode character '\u2421' in position 0: ordinal not in range(256)`

Then if I try to do the same for the `ruby.json`, the previous failed execution somehow corrupt the .jar file `Error: Invalid or corrupt jarfile /usr/local/lib`

Any help?

**Comment by h1994st** [comment]
Will get back to you by the end of this week
